//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Make
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MsgId { get; set; }
        public string MakeText { get; set; }
        public Nullable<int> MakeClick { get; set; }
        public Nullable<System.DateTime> MakeTime { get; set; }
        public string Pic { get; set; }
    
        public virtual Msg Msg { get; set; }
        public virtual User User { get; set; }
    }
}
