//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroBlogEntities : DbContext
    {
        public MicroBlogEntities()
            : base("name=MicroBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Follow_Fans> Follow_Fans { get; set; }
        public virtual DbSet<Make> Make { get; set; }
        public virtual DbSet<Msg> Msg { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
